version: "3"
services:
  mymongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    hostname: mymongo
    volumes:
      - /home/akshith/mongo_backup/:/db
  libraryapi:
    image: libraryapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: libraryapi
    volumes:
      - /home/akshith/library
    depends_on:
      - mymongo
    ports:
      - 3000:3000

