version: "3"
services:
  mymongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    hostname: mymongo
    volumes:
      - /home/akshith/mongo_backup/:/db
  libraryapi:
    image: libraryapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: libraryapi
    environment:
      - EXPRESS_PORT = 3000
      - EXPRESS_HOST = 0.0.0.0
      - MONGODB_CONNECTIONSTRING = mongodb://localhost:27017/librarydata
    volumes:
      - /home/akshith/library
      - /home/akshith/library/node_modules
    depends_on:
      - mymongo
    ports:
      - 3000:3000
    command: nodemon app.js

