version: '3'

services:
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    ports:
      - "27017:27017"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-management-system
    ports:
      - "3000:3000"
    depends_on:
      - mongo
